name: ðŸ§ª PackImage Test via artifact

on:
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-22.04
    steps:
      - name: Download test rootfs
        run: |
          URL="https://github.com/SaeTheOne/openwrt3/releases/download/1.0/immortalwrt-24.10.4-armsr-armv8-generic-rootfs.tar.gz"
          ORIGINAL_NAME=$(basename "$URL")
          wget -O "$ORIGINAL_NAME" "$URL"
          echo "ROOTFS_ORIGINAL_NAME=$ORIGINAL_NAME" >> $GITHUB_ENV
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ROOTFS_ORIGINAL_NAME }}
          path: immortalwrt-24.10.4-armsr-armv8-generic-rootfs.tar.gz

  pack:
    needs: prepare
    uses: ./.github/workflows/pack-image.yml
    secrets: inherit