name: ðŸ§ª PackImage Test via test rootfs

on:
  workflow_dispatch:

jobs:
  pack:
    uses: ./.github/workflows/pack-image.yml
    with:
      rootfs_url: "https://github.com/SaeTheOne/openwrt3/releases/download/1.0/immortalwrt-24.10.4-armsr-armv8-generic-rootfs.tar.gz"
    secrets: inherit